### ISSUE TITLE
Не проблема а вопрос

### ISSUE THREAD

**Issue by viralium** [user95401/gdSmallMods#1]
Так как я новичок в моддинге у меня вопрос:
Есть промежуточные Спрайты как две кнопки и как меню как сделать так чтобы можно было одну(MoreGames)
![image](https://user-images.githubusercontent.com/129858326/232675396-52c21762-8c3a-4636-bce5-b90d5abef7d4.png)

**Comment by viralgmd** [comment]
(чтобы пульсировала только одна)

**Comment by lil2kki** [comment]
ну к меню можно 
menu->setTouchMode(kCCTouchesOneByOne);
объекты в нем будут выбираться по одному

**Comment by viralgmd** [comment]
Не совсем понял

**Comment by lil2kki** [comment]
да я тож вопроса не понял

**Comment by lil2kki** [comment]
есть у тебя меню значит, в нём 2 предмета.
тебе надо чтобы предметы выбирались по отдельности?

**Comment by viralgmd** [comment]
Короче щас обьясню я хочу сделать фанмейд игру по gd мне нужно что-бы кнопка more games пульсировала
Я понял методом тыка что MoreGames находится в 5 индексе но там есть и кнопка выхода из игры

**Comment by viralgmd** [comment]
Да

**Comment by lil2kki** [comment]
а

**Comment by lil2kki** [comment]
добраться до кнопки хочет

**Comment by viralgmd** [comment]
Да

**Comment by viralgmd** [comment]
Не функцию а саму кнопку

**Comment by lil2kki** [comment]
в меню по индексу также получаешь

**Comment by viralgmd** [comment]
А дальше?

**Comment by lil2kki** [comment]
творишь чё хочешь

**Comment by viralgmd** [comment]
Не понял

**Comment by viralgmd** [comment]
Индекс и так ясен

**Comment by viralgmd** [comment]
5.0

**Comment by lil2kki** [comment]
получаешь с начала меню по индексу, а потом и кнопку также в меню

**Comment by viralgmd** [comment]
CCSprite* Menu1 = (CCSprite*)self->getChildren()->objectAtIndex(5);
    Menu1->getChildren()->objectAtIndex(0); так?

**Comment by lil2kki** [comment]
да
но почему CCSprite*?)
CCMenu* Menu1 = (CCMenu*)self->getChildren()->objectAtIndex(5);

**Comment by viralgmd** [comment]
![image](https://user-images.githubusercontent.com/129858326/232716991-6ca90605-2f2d-4618-8316-8ea90d90ce0a.png)
СПС я сам не додумался
